### ISSUE TITLE
where is the "Public " dir and "Site" dir?

### ISSUE THREAD

**Issue by luckypoem** [nakkaya/static#20]
hi.
pls check below.but i don't find the "Public " dir and "Site" dir,where are they?
where is the root dir of the static site?

as3:~/static/target# cp static-app.jar  static.jar ~/static/src/static/
as3:~/static/target# cd ~/static/src/static/
as3:~/static/src/static# ls
config.clj  core.clj  io.clj  static-app.jar  static.jar
as3:~/static/src/static# java -jar static-app.jar --build
[+] INFO: Processing Public  0.002 secs
[+] INFO: Processing Site  0.004 secs
[+] INFO: Build took  0.008 secs
as3:~/static/src/static# ls
config.clj  core.clj  html  io.clj  static-app.jar  static.jar
as3:~/static/src/static# ls html
as3:~/static/src/static# cd ~/static/
as3:~/static# ls
project.clj  readme.org  src  target  test
as3:~/static# ls target
classes  stale  static-app.jar  static.jar
as3:~/static# ls test
static
as3:~/static# ls test/static/
test
as3:~/static# ls test/static/test
core.clj  dummy_fs.clj
as3:~/static#

**Comment by ivangrozni** [comment]
Hey,

I have a similiar issue. This happens if I try to build your nakkaya.com blog as well (for my test org files I also get empty file warning). Markdown works but org mode does not. It might have to do something with emacs (I am actually using spacemacs with emacsclient 26.1).

What I have also tried to run emacs with the config file from config.clj via emacs -q --load /tmp/init.el. This worked for me and all the packages were installed. Any idea?
